# Generated by Django 6.0.2 on 2026-02-19 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('topic', models.CharField(max_length=100)),
                ('difficulty', models.CharField(default='Easy', max_length=20)),
                ('selected_option', models.IntegerField()),
                ('correct_answer', models.IntegerField()),
                ('is_correct', models.BooleanField()),
                ('time_taken', models.IntegerField(help_text='Time taken in seconds')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Practice Activity',
                'verbose_name_plural': 'Practice Activities',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.IntegerField()),
                ('correct_answers', models.IntegerField()),
                ('accuracy', models.FloatField()),
                ('total_time', models.IntegerField(help_text='Total time in seconds')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz Session',
                'verbose_name_plural': 'Quiz Sessions',
                'ordering': ['-completed_at'],
            },
        ),
    ]
